-- Warehouse Compute Validation Queries
-- These queries verify the metrics shown in the Warehouse Compute tab

-- ============================================
-- 1. TOTAL COMPUTE CREDITS (Should show 1,036)
-- ============================================
SELECT 
    SUM(CREDITS_USED_COMPUTE) as TOTAL_COMPUTE_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL;

-- ============================================
-- 2. TOTAL CLOUD SERVICES CREDITS (Should show 77)
-- ============================================
SELECT 
    SUM(CREDITS_USED_CLOUD_SERVICES) as TOTAL_CLOUD_SERVICES_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL;

-- ============================================
-- 3. CURRENT MONTH TOTAL (Should show 66)
-- ============================================
SELECT 
    SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES) as CURRENT_MONTH_TOTAL
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATE_TRUNC('month', CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL;

-- ============================================
-- 4. ACTIVE WAREHOUSES (Should show 37)
-- ============================================
SELECT 
    COUNT(DISTINCT WAREHOUSE_NAME) as ACTIVE_WAREHOUSES
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL
  AND (CREDITS_USED_COMPUTE > 0 OR CREDITS_USED_CLOUD_SERVICES > 0);

-- ============================================
-- 5. DAILY AVERAGE (Should show 6)
-- ============================================
WITH daily_credits AS (
    SELECT 
        DATE(START_TIME) as USAGE_DATE,
        SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES) as DAILY_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
      AND WAREHOUSE_ID > 0
      AND WAREHOUSE_NAME IS NOT NULL
    GROUP BY DATE(START_TIME)
)
SELECT 
    AVG(DAILY_CREDITS) as DAILY_AVERAGE
FROM daily_credits;

-- ============================================
-- 6. CLOUD SERVICES PERCENTAGE (Should show 6.9%)
-- ============================================
SELECT 
    (SUM(CREDITS_USED_CLOUD_SERVICES) / 
     SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES)) * 100 as CLOUD_SERVICES_PERCENTAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL;

-- ============================================
-- 7. PEAK DAILY USAGE (Should show 130)
-- ============================================
WITH daily_credits AS (
    SELECT 
        DATE(START_TIME) as USAGE_DATE,
        SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES) as DAILY_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
      AND WAREHOUSE_ID > 0
      AND WAREHOUSE_NAME IS NOT NULL
    GROUP BY DATE(START_TIME)
)
SELECT 
    MAX(DAILY_CREDITS) as PEAK_DAILY_USAGE
FROM daily_credits;

-- ============================================
-- 8. DATA HISTORY DAYS (Should show 213)
-- ============================================
SELECT 
    DATEDIFF('day', MIN(START_TIME), MAX(START_TIME)) as DATA_HISTORY_DAYS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL;

-- ============================================
-- 9. FULL DATA OVERVIEW (Combined view)
-- ============================================
SELECT 
    'Total Compute Credits' as METRIC,
    SUM(CREDITS_USED_COMPUTE) as VALUE
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL

UNION ALL

SELECT 
    'Total Cloud Services Credits',
    SUM(CREDITS_USED_CLOUD_SERVICES)
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL

UNION ALL

SELECT 
    'Current Month Total',
    SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES)
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATE_TRUNC('month', CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL

UNION ALL

SELECT 
    'Active Warehouses',
    COUNT(DISTINCT WAREHOUSE_NAME)
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL;

-- ============================================
-- 10. BREAKDOWN BY WAREHOUSE (Top 10)
-- ============================================
SELECT 
    WAREHOUSE_NAME,
    SUM(CREDITS_USED_COMPUTE) as COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) as CLOUD_SERVICES_CREDITS,
    SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES) as TOTAL_CREDITS,
    COUNT(*) as USAGE_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_DATE())
  AND WAREHOUSE_ID > 0
  AND WAREHOUSE_NAME IS NOT NULL
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_CREDITS DESC
LIMIT 10;

